---
- name: Update all systems
  hosts: all
  become: true

  pre_tasks:
    - name: Install system updates
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Debian"

# --------------------------------------------

- hosts: workstations
  become: true
  tasks: 

  - name: install unzip
      package:
        name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


# --------------------------------------------

- name: Install Apache with PHP on webservers
  hosts: webservers
  become: true

  tasks:
    - name: Install Apache2
      tags: [apache, apache2, debian]
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Debian"

    - name: Add PHP support for Apache
      apt:
        name:
          - libapache2-mod-php
          - php
        state: latest
      when: ansible_distribution == "Debian"

    - name: Ensure Apache is running and enabled
      service:
        name: apache2
        state: started
        enabled: yes

# --------------------------------------------

- name: Install MariaDB on db servers
  hosts: db_servers
  become: true

  tasks:
    - name: Install MariaDB package (Debian)
      tags: [db, maria, debian]
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Debian"

# --------------------------------------------

- name: Install Samba on file servers
  hosts: file_servers
  become: true

  tasks:
    - name: Install samba package
      tags: [samba]
      package:
        name: samba
        state: latest

